language:
  - node_js

node_js:
  - "5.7"
  - "4.4"
  - "0.12"
  - "0.11"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq php5

install:
  - curl -sS https://getcomposer.org/installer | php

before_script:
  - php composer.phar install
  - npm install -g grunt-cli
  - npm install
